site_name: Aviation Portfolio Pack
site_url: https://barata90.github.io/aviation-portfolio-pack/
repo_url: https://github.com/barata90/aviation-portfolio-pack
repo_name: barata90/aviation-portfolio-pack

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - toc.integrate
    - content.code.copy

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true

nav:
  - Aviation Portfolio Pack: index.md
  - Data Dictionary: data_dictionary.md
  - Quality Report: quality_report.md
  - Case Studies:
      - Emirates (Data Analytics Specialist): case_studies/emirates_data_analytics_specialist.md
  - Pages:
      - Airport Degree: pages/airport_degree.md
      - Dim Airport Clean: pages/dim_airport_clean.md
      - Euro ATFM By Location: pages/euro_atfm_by_location.md
      - Euro ATFM Timeseries: pages/euro_atfm_timeseries.md
      - Route Counts: pages/route_counts.md
      - Top OD Pairs: pages/top_od_pairs.md


plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      type: date
      enable_creation_date: false
      locale: id

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      type: date
      enable_creation_date: false
      locale: id
