site_name: Aviation Portfolio Pack
site_description: Data portfolio — routes, airports, dan ATFM analytics
repo_url: https://github.com/barata90/aviation-portfolio-pack
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - toc.integrate
    - content.code.copy
    
plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      
markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
      
nav:
  - Aviation Portfolio Pack: index.md
  - Data Dictionary: data_dictionary.md
  - Case Studies:
      - Emirates (Data Analytics Specialist): case_studies/emirates_data_analytics_specialist.md
  - Pages:
      - Airport Degree: pages/airport_degree.md
      - Dim Airport Clean: pages/dim_airport_clean.md
      - Euro Atfm By Location: pages/euro_atfm_by_location.md
      - Euro Atfm Timeseries: pages/euro_atfm_timeseries.md
      - Route Counts: pages/route_counts.md
      - Top Od Pairs: pages/top_od_pairs.md
