site_name: Aviation Portfolio Pack
site_url: https://barata90.github.io/aviation-portfolio-pack/
repo_url: https://github.com/barata90/aviation-portfolio-pack
repo_name: barata90/aviation-portfolio-pack

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - toc.integrate
    - content.code.copy

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true

nav:
  - Aviation Portfolio Pack: index.md
  - Data Dictionary: data_dictionary.md
  - Quality Report: quality_report.md
  - Case Studies:
      - Emirates (Data Analytics Specialist): case_studies/emirates_data_analytics_specialist.md
  # Halaman dataset akan ditautkan dari index (dibuat otomatis oleh build_docs.py)
