name: Build data dictionary

# penting: agar GITHUB_TOKEN bisa commit/push
permissions:
  contents: write

on:
  push:
    branches: [ main ]
    # jalankan hanya jika file relevan berubah
    paths:
      - 'scripts/make_data_dictionary.py'
      - 'publish/**'
      - 'docs/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:
  # opsional: rebuild terjadwal tiap tanggal 1 jam 02:05 UTC
  schedule:
    - cron: '5 2 1 * *'

# cegah job tumpang tindih saat push beruntun
concurrency:
  group: data-dict-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false   # biar kredensial tak tertinggal di repo
          fetch-depth: 0               # aman untuk commit/push

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install "duckdb>=1.4.1" pandas openpyxl pyarrow requests

      # jika suatu saat ingin rebuild data mentah/warehouse di CI, tambahkan step sebelum ini
      - name: Re-build data dictionary
        run: |
          python scripts/make_data_dictionary.py \
            --csv-dir publish \
            --tables route_counts,airport_degree,euro_atfm_timeseries,euro_atfm_by_location \
            --out docs/data_dictionary.md

      - name: Commit changes (if any)
        run: |
          if ! git diff --quiet docs/data_dictionary.md; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/data_dictionary.md
            git commit -m "CI: update data dictionary"
          fi

      - name: Push back
        if: success()
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # dorong ke branch yang memicu workflow (biasanya 'main')
          branch: ${{ github.ref_name }}
