name: Build data dictionary

on:
  push:
    branches: [ main ]
    paths:
      - 'publish/**'
      - 'scripts/make_data_dictionary.py'
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'  # mingguan (opsional)

permissions:
  contents: write

concurrency:
  group: 'dictionary'
  cancel-in-progress: true

jobs:
  build-dict:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      # ⬇️ Step sentinel: cek apakah ada CSV di publish/
      - name: Detect CSV presence
        id: csv
        shell: bash
        run: |
          shopt -s nullglob
          files=(publish/*.csv)
          if [ ${#files[@]} -eq 0 ]; then
            echo "has_csv=false" >> "$GITHUB_OUTPUT"
            echo "No CSV in publish/ → skipping downstream steps."
          else
            echo "has_csv=true" >> "$GITHUB_OUTPUT"
            echo "Found ${#files[@]} CSV(s): ${files[*]}"
          fi

      - name: Install deps
        if: steps.csv.outputs.has_csv == 'true'
        run: |
          python -m pip install -U pip
          pip install pandas tabulate duckdb

      - name: Rebuild data dictionary
        if: steps.csv.outputs.has_csv == 'true'
        run: |
          python scripts/make_data_dictionary.py \
            --csv-dir publish \
            --out docs/data_dictionary.md

      - name: Commit if changed
        if: steps.csv.outputs.has_csv == 'true'
        run: |
          if ! git diff --quiet docs/data_dictionary.md; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add docs/data_dictionary.md
            git commit -m "docs: update data dictionary (auto)"
            git push
          else
            echo "No changes."
          fi
