name: Build data dictionary

# Token boleh nulis & bikin PR
permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [ main ]
    paths:
      - 'scripts/make_data_dictionary.py'
      - 'publish/**'
      - 'docs/**'
      - 'requirements.txt'
      - '.github/workflows/build.yml'
  workflow_dispatch:
  # Opsional: jalan tiap tanggal 1 jam 02:05 UTC
  schedule:
    - cron: '5 2 1 * *'

# Hindari dua run saling timpa
concurrency:
  group: data-dictionary
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Re-build data dictionary
        run: |
          python scripts/make_data_dictionary.py \
            --csv-dir publish \
            --tables route_counts,airport_degree,euro_atfm_timeseries,euro_atfm_by_location \
            --out docs/data_dictionary.md

      # Buat PR hanya kalau file berubah
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'CI: update data dictionary'
          title: 'CI: update data dictionary'
          body: |
            Automated update of the data dictionary.
            - Rebuilt from CSVs in `publish/`
          branch: ci/update-data-dictionary
          add-paths: |
            docs/data_dictionary.md
          labels: |
            automation
            data-dictionary
          delete-branch: true

      - name: PR info (if created)
        if: steps.cpr.outputs.pull-request-number != ''
        run: |
          echo "Created PR #${{ steps.cpr.outputs['pull-request-number'] }}"
          echo "URL: ${{ steps.cpr.outputs['pull-request-url'] }}"

      - name: No changes
        if: steps.cpr.outputs.pull-request-number == ''
        run: echo "No changes detected; nothing to commit."
