name: Build data dictionary

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Wajib agar GITHUB_TOKEN bisa push
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true   # biar git pakai GITHUB_TOKEN bawaan

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install duckdb pandas openpyxl pyarrow requests

      # kalau suatu saat mau rebuild data mentah + warehouse di CI, taruh di sini.
      # untuk sekarang kita cuma regenerasi dictionary dari CSV yang ada di publish/

      - name: Re-build data dictionary
        run: |
          python scripts/make_data_dictionary.py \
            --csv-dir publish \
            --tables route_counts,airport_degree,euro_atfm_timeseries,euro_atfm_by_location \
            --out docs/data_dictionary.md

      - name: Commit changes (if any)
        run: |
          if ! git diff --quiet docs/data_dictionary.md; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/data_dictionary.md
            git commit -m "CI: update data dictionary"
          fi

      - name: Push back
        run: |
          # Rebase dulu kalau ada update di remote, supaya push fast-forward
          git pull --rebase origin ${{ github.ref_name }} || true
          # Dorong perubahan (kalau tidak ada perubahan, ini no-op)
          git push origin HEAD:${{ github.ref_name }}
