name: Load to Snowflake

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: 'snowflake-load'
  cancel-in-progress: true

jobs:
  precheck:
    runs-on: ubuntu-latest
    outputs:
      has_secrets: ${{ steps.eval.outputs.has_secrets }}
    steps:
      - id: eval
        shell: bash
        run: |
          if [ -n "${{ secrets.SNOWFLAKE_ACCOUNT }}" ]; then
            echo "has_secrets=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_secrets=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Announce
        run: |
          echo "Snowflake secrets present? -> ${{ steps.eval.outputs.has_secrets }}"
          if [ "${{ steps.eval.outputs.has_secrets }}" != "true" ]; then
            echo "No Snowflake secrets configured; skipping load job."
          fi

  load:
    needs: precheck
    if: needs.precheck.outputs.has_secrets == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install "pandas>=2.0" "pyarrow>=12" "snowflake-connector-python[pandas]"

      - name: Load CSVs to Snowflake
        env:
          SNOWFLAKE_ACCOUNT:   ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER:      ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD:  ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE:      ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE:  ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA:    ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: python scripts/load_to_snowflake.py
