name: Load to Snowflake

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  load:
    # Kalau tidak ada secret SNOWFLAKE_ACCOUNT, job otomatis di-skip (bukan fail)
    if: ${{ secrets.SNOWFLAKE_ACCOUNT != '' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install "pandas>=2.0" "pyarrow>=12" "snowflake-connector-python[pandas]"

      - name: Load CSVs to Snowflake
        env:
          SNOWFLAKE_ACCOUNT:   ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER:      ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD:  ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE:      ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE:  ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA:    ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: python scripts/load_to_snowflake.py
