name: Deploy site

on:
  push:
    branches: [ main ]
    paths:
      - 'publish/**'              # data CSV untuk halaman
      - 'docs/**'                 # markdown & aset
      - 'scripts/build_docs.py'   # generator halaman
      - 'mkdocs.yml'              # konfigurasi MkDocs
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Hanya satu deploy jalan; push terbaru membatalkan yang lama
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install -U pip setuptools wheel
          pip install mkdocs mkdocs-material pandas matplotlib tabulate

      - name: Generate dataset pages (MD + images)
        env:
          MPLBACKEND: Agg        # jaga-jaga: plotting headless
        run: python scripts/build_docs.py

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with MkDocs
        run: mkdocs build --site-dir site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
