name: Deploy site

on:
  push:
    branches: [ main ]
    paths:
      - 'publish/**'
      - 'docs/**'
      - 'scripts/build_docs.py'
      - 'mkdocs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # plugin tanggal akan tetap jalan (fallback) meski depth=1
          # kalau mau histori penuh, set fetch-depth: 0
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps for docs
        run: |
          python -m pip install -U pip
          pip install \
            mkdocs \
            mkdocs-material \
            mkdocs-git-revision-date-localized-plugin \
            pandas \
            matplotlib \
            tabulate

      - name: Generate dataset pages (from publish/*.csv)
        run: python scripts/build_docs.py

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with MkDocs
        run: mkdocs build --site-dir ./site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
