name: Deploy site

on:
  push:
    branches: [ main ]
    paths:
      - 'publish/**'
      - 'docs/**'
      - 'scripts/*.py'
      - 'mkdocs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      - name: Install deps for docs
        run: |
          python -m pip install -U pip
          pip install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin pandas matplotlib tabulate

      - name: Generate dataset pages (from publish/*.csv)
        run: |
          if [ -f scripts/build_docs.py ]; then python scripts/build_docs.py; else echo "skip build_docs.py"; fi

      - name: Build advanced visuals
        run: |
          if [ -f scripts/build_viz_advanced.py ]; then python scripts/build_viz_advanced.py; else echo "skip build_viz_advanced.py"; fi

      - name: Build extras (geojson, sankey, explorer, downloads)
        run: |
          python scripts/build_extras.py
      - name: Include publish data into site
        run: |
          mkdir -p docs/publish
          cp -a publish/. docs/publish/ || true


      - name: Build advanced assets
        run: |
          python scripts/build_adv_assets.py

      - name: Include publish data into site
        run: |
          mkdir -p docs/publish
          cp -a publish/. docs/publish/ || true

      - name: Build ops forecast
        run: |
          python scripts/build_ops_forecast.py || true

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with MkDocs (strict)
        run: mkdocs build --strict --site-dir ./site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
